services:
  - type: web
    name: bfhl-api
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8080
